# Generated by Django 6.0.3 on 2026-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=300, verbose_name='Hujjat nomi')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='admission_documents/', verbose_name='Hujjat fayli')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Izoh')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Talab qilinadigan hujjat',
                'verbose_name_plural': 'Talab qilinadigan hujjatlar',
                'db_table': 'admission_documents',
                'ordering': ['sort_order', 'document_name'],
                'indexes': [models.Index(fields=['is_required'], name='admission_d_is_requ_eec607_idx'), models.Index(fields=['sort_order'], name='admission_d_sort_or_a01b2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name="O'quv yili")),
                ('total_quota', models.PositiveIntegerField(verbose_name="Jami o'rinlar")),
                ('grant_quota', models.PositiveIntegerField(verbose_name="Grant o'rinlari")),
                ('contract_quota', models.PositiveIntegerField(verbose_name="Kontrakt o'rinlari")),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Kontrakt summasi (so'm)")),
                ('application_start', models.DateField(verbose_name='Ariza qabul boshlanishi')),
                ('application_end', models.DateField(verbose_name='Ariza qabul tugashi')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Imtihon sanasi')),
                ('results_date', models.DateField(blank=True, null=True, verbose_name="Natijalar e'lon qilinish sanasi")),
                ('online_apply_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Onlayn ariza havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name="Joriy yil ma'lumoti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': "Qabul ma'lumoti",
                'verbose_name_plural': "Qabul ma'lumotlari",
                'db_table': 'admission_info',
                'ordering': ['-academic_year'],
                'indexes': [models.Index(fields=['academic_year'], name='admission_i_academi_fa186d_idx'), models.Index(fields=['is_active'], name='admission_i_is_acti_c2c992_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('subject_type', models.CharField(choices=[('test', 'Test'), ('essay', 'Insho'), ('interview', 'Intervyu')], default='test', max_length=20, verbose_name='Fan turi')),
                ('max_score', models.PositiveIntegerField(verbose_name='Maksimal ball')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Imtihon fani',
                'verbose_name_plural': 'Imtihon fanlari',
                'db_table': 'admission_subjects',
                'ordering': ['sort_order', 'subject_name'],
                'indexes': [models.Index(fields=['subject_type'], name='admission_s_subject_eed3eb_idx'), models.Index(fields=['sort_order'], name='admission_s_sort_or_cf0206_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol matni')),
                ('answer', models.TextField(verbose_name='Javob matni')),
                ('category', models.CharField(choices=[('admission', 'Qabul'), ('general', 'Umumiy'), ('education', "Ta'lim"), ('payment', "To'lov")], default='general', max_length=20, verbose_name='Kategoriya')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifaga chiqarish')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ lar',
                'db_table': 'faqs',
                'ordering': ['sort_order', 'question'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='faqs_categor_839aa4_idx'), models.Index(fields=['is_featured', 'is_active'], name='faqs_is_feat_5349b6_idx'), models.Index(fields=['sort_order'], name='faqs_sort_or_ea2706_idx')],
            },
        ),
    ]
