# Generated by Django 6.0.3 on 2026-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarsJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=300, verbose_name='Nomi (UZ)')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=300, verbose_name='Nomi (UZ Kirill)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (EN)')),
                ('file', models.FileField(help_text='PDF, DOCX, XLSX va h.k.', upload_to='dars_jadvali/', verbose_name='Jadval fayli')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
                'db_table': 'dars_jadvali',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['sort_order'], name='dars_jadval_sort_or_e8a9ae_idx'), models.Index(fields=['is_active'], name='dars_jadval_is_acti_cc42f4_idx')],
            },
        ),
    ]
