# Generated by Django 6.0.3 on 2026-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_dars_jadvali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiondocument',
            name='document_name_en',
        ),
        migrations.RemoveField(
            model_name='admissiondocument',
            name='document_name_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='admissiondocument',
            name='note_en',
        ),
        migrations.RemoveField(
            model_name='admissiondocument',
            name='note_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='admissionsubject',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='admissionsubject',
            name='description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='admissionsubject',
            name='subject_name_en',
        ),
        migrations.RemoveField(
            model_name='admissionsubject',
            name='subject_name_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='darsjadvali',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='darsjadvali',
            name='title_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_uz_cyrl',
        ),
    ]
