# Generated by Django 6.0.3 on 2026-04-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="To'garak nomi")),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('art', "San'at"), ('science', 'Fan'), ('language', 'Til'), ('tech', 'Texnologiya'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name="Maksimal o'rinlar")),
                ('current_students', models.PositiveIntegerField(default=0, verbose_name="Hozirgi o'quvchilar soni")),
                ('schedule', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dars vaqti')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Xona')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='circles/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circles', to='structure.teacher', verbose_name="Rahbar o'qituvchi")),
            ],
            options={
                'verbose_name': "To'garak",
                'verbose_name_plural': "To'garaklar",
                'db_table': 'circles',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='circles_slug_08b39c_idx'), models.Index(fields=['category', 'is_active'], name='circles_categor_640276_idx'), models.Index(fields=['is_active', 'sort_order'], name='circles_is_acti_ed26ec_idx')],
            },
        ),
    ]
