# Generated by Django 6.0.3 on 2026-04-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0003_alter_department_id_alter_management_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Nomi (UZ)')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=200, verbose_name='Nomi (UZ Kirill)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (EN)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ)')),
                ('description_uz_cyrl', models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ Kirill)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (EN)')),
                ('schedule_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dars vaqti (UZ)')),
                ('schedule_uz_cyrl', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dars vaqti (UZ Kirill)')),
                ('schedule_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dars vaqti (RU)')),
                ('schedule_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dars vaqti (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('art', "San'at"), ('science', 'Fan'), ('language', 'Til'), ('tech', 'Texnologiya'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name="Maksimal o'rinlar")),
                ('current_students', models.PositiveIntegerField(default=0, verbose_name="Hozirgi o'quvchilar soni")),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Xona')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='circles/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circles', to='structure.teacher', verbose_name="Rahbar o'qituvchi")),
            ],
            options={
                'verbose_name': "To'garak",
                'verbose_name_plural': "To'garaklar",
                'db_table': 'circles',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['slug'], name='circles_slug_08b39c_idx'), models.Index(fields=['category', 'is_active'], name='circles_categor_640276_idx'), models.Index(fields=['is_active', 'sort_order'], name='circles_is_acti_ed26ec_idx')],
            },
        ),
    ]
