# Generated by Django 6.0.3 on 2026-04-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Album nomi')),
                ('slug', models.SlugField(max_length=350, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery_covers/', verbose_name='Muqova rasmi')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Tadbir sanasi')),
                ('photos_count', models.PositiveIntegerField(default=0, verbose_name='Rasmlar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Galereya albomi',
                'verbose_name_plural': 'Galereya albomlari',
                'db_table': 'gallery_albums',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='gallery_alb_slug_dfce4b_idx'), models.Index(fields=['is_active', 'sort_order'], name='gallery_alb_is_acti_639007_idx'), models.Index(fields=['event_date'], name='gallery_alb_event_d_2eb53b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('url', models.URLField(max_length=500, verbose_name='Havola')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='useful_links_logos/', verbose_name='Logo rasm')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Foydali havola',
                'verbose_name_plural': 'Foydali havolalar',
                'db_table': 'useful_links',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='useful_link_is_acti_400833_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos/', verbose_name='Asosiy rasm')),
                ('thumbnail', models.ImageField(upload_to='gallery_thumbnails/', verbose_name='Kichik rasm')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='Izoh')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.galleryalbum', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'db_table': 'gallery_photos',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['album', 'sort_order'], name='gallery_pho_album_i_7aa150_idx'), models.Index(fields=['created_at'], name='gallery_pho_created_490ee2_idx')],
            },
        ),
    ]
