# Generated by Django 6.0.3 on 2026-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryalbum',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='title',
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='title_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='title_uz_cyrl',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nomi (UZ Kirill)'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_thumbnails/', verbose_name='Kichik rasm'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='useful_links_logos/', verbose_name='Logo'),
        ),
    ]
