# Generated by Django 6.0.3 on 2026-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_galleryalbum_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=300, verbose_name='Nomi (UZ)')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=300, verbose_name='Nomi (UZ Kirill)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_uz_cyrl', models.TextField(blank=True, verbose_name='Tavsif (UZ Kirill)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('image', models.ImageField(upload_to='infrastructure/', verbose_name='Rasm')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Moddiy-texnik baza elementi',
                'verbose_name_plural': 'Moddiy-texnik baza',
                'db_table': 'infrastructure_items',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='infrastruct_is_acti_8f6270_idx')],
            },
        ),
    ]
