# Generated by Django 6.0.3 on 2026-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_infrastructureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (UZ)')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (UZ Kirill)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_uz_cyrl', models.TextField(blank=True, verbose_name='Tavsif (UZ Kirill)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video fayl (mp4, webm va boshqalar)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Muqova rasmi')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Video lavha',
                'verbose_name_plural': 'Video lavhalar',
                'db_table': 'gallery_videos',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='gallery_vid_is_acti_4f83f4_idx'), models.Index(fields=['created_at'], name='gallery_vid_created_edadab_idx')],
            },
        ),
    ]
