# Generated by Django 6.0.3 on 2026-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryalbum',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='title_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='title_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title_uz_cyrl',
        ),
    ]
