# Generated by Django 6.0.3 on 2026-04-16 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism-familiya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('subject', models.CharField(choices=[('admission', 'Qabul'), ('general', 'Umumiy savol'), ('complaint', 'Shikoyat'), ('suggestion', 'Taklif'), ('other', 'Boshqa')], default='general', max_length=20, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('replied', 'Javob berilgan'), ('archived', 'Arxivlangan')], default='new', max_length=20, verbose_name='Holat')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Javob')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name="Brauzer ma'lumoti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies', to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_mes_created_684d0e_idx'), models.Index(fields=['status', '-created_at'], name='contact_mes_status_060932_idx'), models.Index(fields=['email'], name='contact_mes_email_a7fb56_idx')],
            },
        ),
    ]
