# Generated by Django 6.0.3 on 2026-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Kalit')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Qiymat')),
                ('label', models.CharField(max_length=100, verbose_name='Yorliq (frontendda chiqadigan matn)')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon classi')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['sort_order'],
            },
        ),
    ]
