# Generated by Django 6.0.3 on 2026-04-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='label',
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Yorliq (EN)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Yorliq (RU)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Yorliq (UZ)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_uz_cyrl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Yorliq (UZ Kirill)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon classi (masalan: fa-users)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kalit (texnik)'),
        ),
        migrations.AlterModelTable(
            name='statistic',
            table='statistics',
        ),
    ]
