# Generated by Django 6.0.3 on 2026-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_statistic_label_statistic_label_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='label_uz_cyrl',
        ),
    ]
