# Generated by Django 6.0.3 on 2026-04-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kafedra nomi')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('subjects', models.JSONField(blank=True, default=list, null=True, verbose_name="Fanlar ro'yxati")),
                ('room_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Xona raqami')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
                'db_table': 'departments',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ismi")),
                ('position', models.CharField(max_length=200, verbose_name='Lavozimi')),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ilmiy daraja')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('reception_hours', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qabul vaqti')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='management_photos/', verbose_name='Rasm')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbariyat',
                'db_table': 'management',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='management_is_acti_122798_idx')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ismi")),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozimi')),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ilmiy daraja')),
                ('academic_rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ilmiy unvon')),
                ('category', models.CharField(choices=[('highest', 'Oliy toifa'), ('first', 'Birinchi toifa'), ('second', 'Ikkinchi toifa'), ('none', 'Toifasiz')], default='none', max_length=10, verbose_name='Toifa')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ish staji (yil)')),
                ('subject', models.CharField(max_length=200, verbose_name="O'qitadigan fan")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Rasm')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Yutuqlar')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='structure.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'db_table': 'teachers',
                'ordering': ['sort_order', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='structure.teacher', verbose_name='Kafedra mudiri'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['slug'], name='teachers_slug_21b489_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department', 'is_active'], name='teachers_departm_bc222d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['category', 'is_active'], name='teachers_categor_3f0e17_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['slug'], name='departments_slug_b4a8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active', 'sort_order'], name='departments_is_acti_5e04b5_idx'),
        ),
    ]
