# Generated by Django 6.0.3 on 2026-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_department_id_alter_management_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['sort_order', 'name_uz'], 'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='management',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='management',
            name='position',
        ),
        migrations.RemoveField(
            model_name='management',
            name='reception_hours',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uz_cyrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='management',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (EN)'),
        ),
        migrations.AddField(
            model_name='management',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (RU)'),
        ),
        migrations.AddField(
            model_name='management',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (UZ)'),
        ),
        migrations.AddField(
            model_name='management',
            name='bio_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='management',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (EN)'),
        ),
        migrations.AddField(
            model_name='management',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (RU)'),
        ),
        migrations.AddField(
            model_name='management',
            name='position_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (UZ)'),
        ),
        migrations.AddField(
            model_name='management',
            name='position_uz_cyrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='management',
            name='reception_hours_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qabul vaqti (EN)'),
        ),
        migrations.AddField(
            model_name='management',
            name='reception_hours_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qabul vaqti (RU)'),
        ),
        migrations.AddField(
            model_name='management',
            name='reception_hours_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qabul vaqti (UZ)'),
        ),
        migrations.AddField(
            model_name='management',
            name='reception_hours_uz_cyrl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qabul vaqti (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='achievements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Yutuqlar (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='achievements_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Yutuqlar (RU)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='achievements_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Yutuqlar (UZ)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='achievements_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Yutuqlar (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (RU)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (UZ)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (EN)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (RU)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (UZ)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_uz_cyrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozimi (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_en',
            field=models.CharField(blank=True, max_length=200, verbose_name="O'qitadigan fan (EN)"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name="O'qitadigan fan (RU)"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name="O'qitadigan fan (UZ)"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_uz_cyrl',
            field=models.CharField(blank=True, max_length=200, verbose_name="O'qitadigan fan (UZ Kirill)"),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
