# Generated by Django 6.0.3 on 2026-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy daraja'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_rank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy unvon'),
        ),
    ]
