# Generated by Django 6.0.3 on 2026-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_teacher_academic_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='management',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='management',
            name='bio_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='management',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='management',
            name='position_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='management',
            name='reception_hours_en',
        ),
        migrations.RemoveField(
            model_name='management',
            name='reception_hours_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='achievements_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='achievements_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_uz_cyrl',
        ),
    ]
