# Generated by Django 6.0.3 on 2026-04-09 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (UZ)')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (UZ Kirill)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (EN)')),
                ('short_description_uz', models.TextField(blank=True, verbose_name='Qisqa tavsif (UZ)')),
                ('short_description_uz_cyrl', models.TextField(blank=True, verbose_name='Qisqa tavsif (UZ Kirill)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Qisqa tavsif (RU)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Qisqa tavsif (EN)')),
                ('content_uz', models.TextField(blank=True, verbose_name='Matn (UZ)')),
                ('content_uz_cyrl', models.TextField(blank=True, verbose_name='Matn (UZ Kirill)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (EN)')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement_images/', verbose_name='Asosiy rasm')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('is_important', models.BooleanField(default=False, verbose_name="Muhim e'lon")),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Holat')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Muddati tugash sanasi')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'db_table': 'announcements',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_important'], name='announcemen_status_3f1f53_idx'), models.Index(fields=['slug'], name='announcemen_slug_b1a99c_idx'), models.Index(fields=['-published_at'], name='announcemen_publish_4a0d1e_idx'), models.Index(fields=['expires_at'], name='announcemen_expires_e08bf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (UZ)')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (UZ Kirill)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (EN)')),
                ('short_description_uz', models.TextField(blank=True, verbose_name='Qisqa tavsif (UZ)')),
                ('short_description_uz_cyrl', models.TextField(blank=True, verbose_name='Qisqa tavsif (UZ Kirill)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Qisqa tavsif (RU)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Qisqa tavsif (EN)')),
                ('content_uz', models.TextField(blank=True, verbose_name='Matn (UZ)')),
                ('content_uz_cyrl', models.TextField(blank=True, verbose_name='Matn (UZ Kirill)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (EN)')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Asosiy rasm')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifaga chiqarish')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='news_status_1ff369_idx'), models.Index(fields=['slug'], name='news_slug_fb3ac9_idx'), models.Index(fields=['-published_at'], name='news_publish_efe204_idx')],
            },
        ),
    ]
