# Generated by Django 6.0.3 on 2026-04-08 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=350, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Qisqa tavsif')),
                ('content', models.TextField(verbose_name="To'liq matn")),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rasm URL')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('is_important', models.BooleanField(default=False, verbose_name="Muhim e'lon")),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Holat')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Muddati tugash sanasi')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'db_table': 'announcements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rasm izohi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.announcement', verbose_name="E'lon")),
            ],
            options={
                'verbose_name': "E'lon rasmi",
                'verbose_name_plural': "E'lon rasmlari",
                'db_table': 'announcement_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=350, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Qisqa tavsif')),
                ('content', models.TextField(verbose_name="To'liq matn")),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True, verbose_name='Asosiy rasm URL')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifaga chiqarish')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rasm izohi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangilik rasmlari',
                'db_table': 'news_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'is_important'], name='announcemen_status_3f1f53_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['slug'], name='announcemen_slug_b1a99c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-published_at'], name='announcemen_publish_4a0d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expires_at'], name='announcemen_expires_e08bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementimage',
            index=models.Index(fields=['announcement', 'sort_order'], name='announcemen_announc_63369a_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', 'is_featured'], name='news_status_1ff369_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_slug_fb3ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at'], name='news_publish_efe204_idx'),
        ),
        migrations.AddIndex(
            model_name='newsimage',
            index=models.Index(fields=['news', 'sort_order'], name='news_images_news_id_c5873c_idx'),
        ),
    ]
