# Generated by Django 6.0.3 on 2026-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='content_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='short_description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_uz_cyrl',
        ),
    ]
