# Generated by Django 6.0.3 on 2026-06-25 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_announcement_content_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='news_status_1ff369_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='short_description_uz',
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status'], name='news_status_66f3e7_idx'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description_uz',
        ),
    ]
