# Generated by Django 5.1.4 on 2026-04-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Qisqa nomi')),
                ('full_name', models.CharField(max_length=300, verbose_name="To'liq nomi")),
                ('established_year', models.PositiveIntegerField(verbose_name='Tashkil etilgan yili')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Sozlamalar',
                'verbose_name_plural': 'Sozlamalar',
                'db_table': 'site_settings',
            },
        ),
    ]
