# Generated by Django 6.0.3 on 2026-04-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Sayt sozlamalari', 'verbose_name_plural': 'Sayt sozlamalari'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='short_name',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uz_cyrl',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=300, verbose_name="To'liq nomi (EN)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name="To'liq nomi (RU)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name="To'liq nomi (UZ)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='full_name_uz_cyrl',
            field=models.CharField(blank=True, max_length=300, verbose_name="To'liq nomi (UZ Kirill)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_name_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_name_uz_cyrl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi (UZ Kirill)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='established_year',
            field=models.PositiveIntegerField(default=2000, verbose_name='Tashkil etilgan yili'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
    ]
