# Generated by Django 6.0.3 on 2026-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Rasm')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (UZ)')),
                ('title_uz_cyrl', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (UZ Kirill)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_uz_cyrl', models.TextField(blank=True, verbose_name='Tavsif (UZ Kirill)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slayderlar',
                'db_table': 'slider',
                'ordering': ['sort_order'],
            },
        ),
    ]
