# Generated by Django 6.0.3 on 2026-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='full_name_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='short_name_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='short_name_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_uz_cyrl',
        ),
    ]
